matrix:
  include:
    - language: cpp
      compiler:
        - gcc
      os:
       - linux
       - osx
    - language: java
      jdk: 
        - oraclejdk8
        - openjdk8

before_install:
  - git submodule update --init --recursive

install: mvn install -DskipTests=true -Dgpg.skip=true

after_success:
  - mvn clean test integration-test